name: merge-values
version: 0.6.7.1
usage: Merge Values files
description: This plugin merges values files for debugging purposes
ignoreFlags: false
command: $HELM_PLUGIN_DIR\.venv\Scripts\python.exe $HELM_PLUGIN_DIR/helm_merge_values/main.py
#hooks:
#  install: $HELM_PLUGIN_DIR/helm_kubeconform/install.sh