name: merge-values
version: 1.0.0
usage: Merge Values files
description: merge values files
ignoreFlags: false
command: $HELM_PLUGIN_DIR\.venv\Scripts\python.exe $HELM_PLUGIN_DIR/helm_merge_values/main.py
platformCommand:
  - os: linux
    command: '"$HELM_PLUGIN_DIR"/venv/bin/python3 "$HELM_PLUGIN_DIR"/helm_merge_values/main.py'
  - os: windows
    command: '"$HELM_PLUGIN_DIR"\venv\bin\python3.exe "$HELM_PLUGIN_DIR"\helm_merge_values\main.py'