name: merge-values
version: 1.0.0
usage: Merge Values files
description: merge values files and output them to STD_OUT
ignoreFlags: false
command: $HELM_BIN template $HELM_PLUGIN_DIR\helm_merge_values
platformCommand:
  - os: linux
    command: "$HELM_BIN template $HELM_PLUGIN_DIR/helm_merge_values"
  - os: windows
    command: "$HELM_BIN template $HELM_PLUGIN_DIR\\helm_merge_values"